### PR TITLE
2016 docker dev

### PR DESCRIPTION
**Pull request by jgmize**
@hoosteeno & @stephaniehobson I've set up https://ci.us-west.moz.works/view/viewsourceconf/job/viewsourceconf_deploy_stage/ to automatically deploy to https://viewsourceconf-stage.us-west.moz.works from master, which will work once this PR is merged. The job is configured to run the `make build-deploy` command implemented in this PR with the appropriate credentials and environment variables. I previously configured that job to build from this branch, and here is an example of a successful run: https://ci.us-west.moz.works/view/viewsourceconf/job/viewsourceconf_deploy_stage/9/console

There is more work to be done in the form of documentation of the local docker dev env and automatic deploys of tagged commits to production, which I will address with future PRs.

### CODE REVIEW

**Comment by hoosteeno** [comment]
This is fantastic -- thank you @jgmize!
Just so I'm clear: Should we treat the docker-dev branch as our working branch, or would you recommend we hack elsewhere and merge to this on special occasions?

**Comment by hoosteeno** [comment]
Oh, I just realized there is a disconnect.

I think we need to auto-deploy to stage from a branch, because I think we won't want to merge to master until we're ready to replace the production site with what's in master. Do you think this makes sense?

That contextualizes my question above. We should be treating some branch as our working branch -- is it this one?

**Comment by jgmize** [comment]
> I think we need to auto-deploy to stage from a branch, because I think we won't want to merge to master until we're ready to replace the production site with what's in master. Do you think this makes sense?

> That contextualizes my question above. We should be treating some branch as our working branch -- is it this one?

I assumed it would be easier for you to just work out of the master branch, but we can easily configure jenkins to deploy from a different branch if you'd prefer. How about I push this to the `2016` branch you created earlier and configure Jenkins to deploy stage from that branch instead?

**Comment by jgmize** [comment]
Closing in favor of #36

**Pull request closed without merging**
