### PR TITLE
Landing page tweaks.

### LINKED ISSUE #74: Optimize landing page for conference subpages
We're going to change some layout, copy, and styles on the landing page to see if we can boost the number of people going to a conference subpage. Details:

* use the "bright" class on berlin/seattle buttons -- make them white
* make the copy on buttons bold
* make the top logo smaller -- 200px wide
* replace the main event text on the landing page:

>View Source is a conference for developers, by developers, where we explore best practices and exciting new techniques in web development and design. 
> 
> 1 track, 2 conference days, 16 amazing main stage speakers, lively breakout discussions, Q&A with industry experts, lightning talks, and just 500 available seats. 
> 
> Don't miss these View Source Conferences in 2016! 
>
> [In Europe, View Source will be held at the beautiful, riverfront Radialsystem in Berlin Mitte, September 12-14]. 
> 
> [In North America, View Source will be in downtown Seattle, November 1-3 at Benaroya Hall], home of the Seattle Symphony.

### PR DESCRIPTION
**Pull request by stephaniehobson**
- [x] use the "bright" class on berlin/seattle buttons
- [x] make the copy on buttons bold
- [x] make the top logo 200px wide and decrease padding on tall screens
- [x] replace the main event text on the landing page

Fix #74

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Need yay or nay on my suggested changes to the text discussed in #74.

**Comment by hoosteeno** [comment]
2 things on this...
* I guess we need a rebase after email changes
* I somehow forgot to add...

- [ ] Change "Learn More" to "Get info and tickets" on both buttons

**Comment by stephaniehobson** [comment]
Rebased ⚡

**Comment by hoosteeno** [comment]
R+. I attempted a rebase PR on this branch, which I think means it is safe to merge. Let's see! :zap:

**Pull request merged**
